### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bcurran3** [dmzx/Copyright-in-footer#1]
Works great.

FEATURE REQUEST:
Add it to bottom of all print previews/print outputs as well.

**Comment by dmzx** [comment]
There are no events in the correct place at the print pages.
See for example https://github.com/phpbb/phpbb/blob/7ccb19fa001cb0f76499fd19256e60df382c6d2a/phpBB/styles/prosilver/template/viewtopic_print.html#L39

**Comment by bcurran3** [comment]
Bummer.
